# 文件路径：.github/workflows/sync-upstream.yml
name: Sync Fork with LibreSpark/LibreTV

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点触发（北京时间早上8点）
  workflow_dispatch:     # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/LibreSpark/LibreTV.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into local main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      - name: Push changes to fork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push origin main
